server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: vacation
          uri: http://localhost:8081
          predicates:
            - Path=/vacations/**, /vacationDaysLefts/**, /vacationDaysStatuses/**, /vacationStatuses/**
        - id: schedule
          uri: http://localhost:8082
          predicates:
            - Path=/calendars/**, /searchCalendars/**
        - id: employee
          uri: http://localhost:8083
          predicates:
            - Path=/employees/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

      rsocket:
        id: ${spring.profiles}
        route-id: 1
        brokers:
          - host: localhost
            port: 7000
---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: vacation
          uri: http://vacation:8080
          predicates:
            - Path=/vacations/**, /vacationDaysLefts/**, /vacationDaysStatuses/**, /vacationStatuses/**
        - id: schedule
          uri: http://schedule:8080
          predicates:
            - Path=/calendars/**, /searchCalendars/**
        - id: employee
          uri: http://employee:8080
          predicates:
            - Path=/employees/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
